#!/bin/sh

source ~/miniconda3/etc/profile.d/conda.sh
conda activate vbftrigger

python /eos/user/j/jkil/SUEP/vbftrigger/efficiency/EfficiencyAnalysis.py --whichfiles="singlemuon" --triggerpath="pt105Analysis" --analysis="LeadJetchEmEFAnalysis" --outputdir="/eos/user/j/jkil/www/VBFSUEP/efficiency/withJetLevelHLT/" --shape=True --tightcuts=True --datapath=/eos/user/j/jkil/SUEP/vbftrigger/efficiency/2023CD_parquets/ &> /afs/cern.ch/user/j/jkil/efficiencyanalysis/batchlogs/LeadJetchEmEFAnalysis_tight.log
python /eos/user/j/jkil/SUEP/vbftrigger/efficiency/EfficiencyAnalysis.py --whichfiles="singlemuon" --triggerpath="pt105Analysis" --analysis="LeadJetchHEFAnalysis" --outputdir="/eos/user/j/jkil/www/VBFSUEP/efficiency/withJetLevelHLT/" --shape=True --tightcuts=True --datapath=/eos/user/j/jkil/SUEP/vbftrigger/efficiency/2023CD_parquets/ &> /afs/cern.ch/user/j/jkil/efficiencyanalysis/batchlogs/LeadJetchHEFAnalysis_tight.log
python /eos/user/j/jkil/SUEP/vbftrigger/efficiency/EfficiencyAnalysis.py --whichfiles="singlemuon" --triggerpath="pt105Analysis" --analysis="LeadJetneEmEFAnalysis" --outputdir="/eos/user/j/jkil/www/VBFSUEP/efficiency/withJetLevelHLT/" --shape=True --tightcuts=True --datapath=/eos/user/j/jkil/SUEP/vbftrigger/efficiency/2023CD_parquets/ &> /afs/cern.ch/user/j/jkil/efficiencyanalysis/batchlogs/LeadJetneEmEFAnalysis_tight.log
python /eos/user/j/jkil/SUEP/vbftrigger/efficiency/EfficiencyAnalysis.py --whichfiles="singlemuon" --triggerpath="pt105Analysis" --analysis="LeadJetneHEFAnalysis" --outputdir="/eos/user/j/jkil/www/VBFSUEP/efficiency/withJetLevelHLT/" --shape=True --tightcuts=True --datapath=/eos/user/j/jkil/SUEP/vbftrigger/efficiency/2023CD_parquets/ &> /afs/cern.ch/user/j/jkil/efficiencyanalysis/batchlogs/LeadJetneHEFAnalysis_tight.log
python /eos/user/j/jkil/SUEP/vbftrigger/efficiency/EfficiencyAnalysis.py --whichfiles="singlemuon" --triggerpath="pt105Analysis" --analysis="LeadJetmuEFAnalysis" --outputdir="/eos/user/j/jkil/www/VBFSUEP/efficiency/withJetLevelHLT/" --shape=True --tightcuts=True --datapath=/eos/user/j/jkil/SUEP/vbftrigger/efficiency/2023CD_parquets/ &> /afs/cern.ch/user/j/jkil/efficiencyanalysis/batchlogs/LeadJetmuEFAnalysis_tight.log
